apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  progressDeadlineSeconds: 600  # Increased timeout to 10 minutes (default is 600 seconds)
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: adam649/testrepo:latest # Replace with your Docker image tag if needed
          command: ["python", "/opt/app/dronedemo/main.py"]  # Ensure correct startup command
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: production # Set the Flask environment to production
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
